Task-2

In [1]:
import numpy as np

# Create a 1D NumPy array of length 12
arr = np.arange(12)

# Reshape the array into a 2D array of shape (3, 4)
reshaped_arr = arr.reshape(3, 4)

print(reshaped_arr)


c:\Users\Dhwanil Chauhan\Desktop\internship
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Task-3

In [2]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 5, 3, 2, 4])

# Find the minimum and maximum values
minimum = np.min(arr)
maximum = np.max(arr)

print("Minimum:", minimum)
print("Maximum:", maximum)

Minimum: 1
Maximum: 5


Task-4

In [3]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the mean, median, and standard deviation
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


Task-5

In [4]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Extract the odd numbers using boolean indexing
odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)

[1 3 5]
